---
title: "realtime_forecast_eval"
author: "Alessandro Ciancetta"
date: "2023-06-01"
output: html_document
params: 
  eval: FALSE
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "rendered_notebooks") })
---

# Forecast evaluation

```{r message=FALSE, warning=FALSE, results = "hide", include=FALSE}
library(tidyverse)
library(lubridate)
library(gridExtra)
library(kableExtra)
```



```{r message=FALSE, warning=FALSE, results = "hide"}
## Load code from script folders
preprocessing_scripts_env <- new.env()    
file.sources = list.files(paste0(getwd(), "/sourcecode"),
                          pattern=".R$", full.names=TRUE, 
                          ignore.case=TRUE, recursive = TRUE)
sapply(file.sources, source, preprocessing_scripts_env)
attach(preprocessing_scripts_env, name="sourced_scripts")
```


## Data preparation

```{r message=FALSE, warning=FALSE, results = "hide"}
## Load data
target_variables <- c("UNRATE", "W875RX1", "GS10", "CPIAUCSL", "WPSFD49207", "PAYEMS", "HOUST", "INDPRO", "M2SL", "S.P.500")
target_variables <- c("UNRATE", "CPIAUCSL", "INDPRO", "S&P 500")
```


```{r eval = FALSE, message=FALSE, warning=FALSE, results = "hide"}
## Prepare data list 
# fred.files <- list.files("data/fredmd_vintages/", full.names = TRUE)
# fred_list <- sapply(fred.files, read_csv)
# 
# ## The window size here will be the lenght of the first available vintage
# window_size <- nrow(fred_list[[1]])-1
# 
# d_list_nowindow <- pbapply::pblapply(fred_list, preprocess_fredmd, impute = TRUE)
# d_list <- pbapply::pbsapply(1:length(d_list_nowindow), 
#                                    function(i){d_list_nowindow[[i]][i:(i+nrow(d_list_nowindow[[1]])-1), ]} )
# d_list_window <- d_list_window[[1:283]] |> tail()
# saveRDS(d_list_window, file = "data/fredmd_vintages/evaluationlist_windowsize487_imputeTRUE_pseudoFALSE.RDS")
```


```{r eval = FALSE, message=FALSE, warning=FALSE, results = "hide"}
## Get TV-PCs
# num_cores <- parallel::detectCores()-1
# get_tvpc_cmp <- compiler::cmpfun(get_tvpc)
# for(target in target_variables){
#     target <- "S&P 500"
#     cat("\ntarget = ", target, "\n")
#     file_name <- paste0("data/fredmd_vintages/componentlist400_", target,"_windowsize", window_size, "_pseudoFALSE.RDS")
#     cl <- parallel::makeCluster(num_cores)
#     pc_list <- pbapply::pblapply(d_list, get_tvpc_cmp, target, k=400, cl = cl)
#     parallel::stopCluster(cl)
#     saveRDS(pc_list, file = file_name)
#     cat("\nPrincipal component list successfully saved as ", file_name)
# }
```




## Forecast evaluation

```{r}
## Setup evaluation
horizon <- 6
pseudo <- FALSE      # pseudo real time
window_size <- 487   # size of the rolling window

## Set number of cores for parallel execution
num_cores <- parallel::detectCores() - 1
## String summarising evaluation setup
setup_name <- paste0("_horizon", horizon, "_windowsize", window_size, "_pseudo", as.character(pseudo))

```

```{r}
## Collect setup in a simple function
run_evaluation <- function(m, ...){
    res <- forecast_evaluation_fredmd(forecaster = m, 
                                      ...,
                                      horizon = horizon,
                                      fredmd = NULL,
                                      target = target_variables,
                                      window_size = window_size,
                                      pseudo = pseudo,
                                      num_cores = num_cores,
                                      verbose = TRUE,
                                      impute = TRUE)

  ## Save results to disk
  filename <- paste0("results/", deparse(substitute(m)), ..., setup_name)
  saveRDS(object = res, file = filename)
  
  ## Output results
  res
}

## compile
run_evaluation <- compiler::cmpfun(run_evaluation)
```




### Principal Component Regression (PCR)

```{r eval=params$eval}
pcr_res <- run_evaluation(pcr_reg)
```



### Kernel PCR - Gaussian kernel

```{r eval=params$eval}
kernelgauss_res <- run_evaluation(kernel_pcr, kernel = "gaussian", sigma = 0.001)
```



### Diffusion map

```{r eval=params$eval}
diffusionmap_res <- run_evaluation(diffusion_map_reg)
```



### RTNSE

```{r rtsne, eval=params$eval}
rtsne_res <- run_evaluation(rtsne_reg)
```



### DFM

```{r eval=params$eval}
#expm
# install.packages('expm')
library(expm)
dfm_res <- run_evaluation(dfm)
```



### LASSO TV-PCR 

```{r lasso, eval = params$eval}
## Run variable by variable to load variable-specific training data and components
tvpcr_lasso_res <- list()
for(i in 1:length(target_variables)){
  cat("\n", target_variables[i], " (number ", i, " of ", length(target_variables), ")\n", sep = "")
  tvpcr_lasso_res[[i]] <- forecast_evaluation_fredmd(forecaster = tvpcr, 
                                                      n_components = 400,
                                                      horizon = horizon,
                                                      tuning = NULL,
                                                      regularization = "lasso",
                                                      fredmd = NULL,
                                                      target = target_variables[i],
                                                      window_size = window_size,
                                                      pseudo = pseudo,
                                                      num_cores = num_cores,
                                                      verbose = TRUE,
                                                      load_components = TRUE)
}

## Collect results
tvpcr_lasso_res <- collect_results(tvpcr_lasso_res)
saveRDS(tvpcr_lasso_res, paste0("results/tvpcr_lasso", setup_name))
```





### D2FM

```{r eval=params$eval}
## Setup Python environment
# install.packages('reticulate')
library(reticulate)

## Select the version of python
reticulate::use_python("C:/Users/aless/AppData/Local/Programs/Python/Python310/python.exe", required = TRUE)
#reticulate::use_python("/Users/utente/Library/Frameworks/Python.framework/Versions/3.10/bin/python3", required = TRUE)

## Source the script
reticulate::source_python("sourcecode/forecast_evaluation/forecast_algorithms/D2FM.py")
## Load needed Python libraries
torch <- import("torch")
nn <- import("torch.nn")
optim <- import("torch.optim")
lr_scheduler <- import("torch.optim.lr_scheduler")
ExponentialLR <- lr_scheduler$ExponentialLR
data_python <- import("torch.utils.data")
Dataset <- data_python$Dataset
DataLoader <- data_python$DataLoader
pd <- import("pandas")
np <- import("numpy")
plt <- import("matplotlib.pyplot")
sys = import('sys')
```


```{r eval=params$eval}
d2fm_res <- forecast_evaluation_fredmd(forecaster = d2fm,
                                       latent_size = 10, 
                                       hidden_layer_sizes = tuple(30L, convert = FALSE),
                                       hidden_size_gru = 1, 
                                       num_layers_gru = 1, 
                                       seq_length = 12,
                                       epochs = 150,
                                       horizon = horizon,
                                       fredmd = NULL,
                                       target = NULL,   # all the variables are predicted
                                       window_size = window_size,
                                       pseudo = pseudo,
                                       num_cores = 1,
                                       verbose = TRUE)

## Select target variables only
d2fm_res$forecasts <- d2fm_res$forecasts |> select(any_of(c("sasdate", "dates_name", target_variables))) |> rename(sasdate = dates_name)
d2fm_res$ground_truth <- d2fm_res$ground_truth |> select(any_of(c("sasdate", "dates_name", target_variables)))
d2fm_res$forecast_errors <- d2fm_res$forecast_errors |> select(any_of(c("sasdate", "dates_name", target_variables)))  |> rename(sasdate = dates_name)

## Save results
saveRDS(d2fm_res, file =  paste0("results/d2fm", setup_name))
```

